### ISSUE TITLE
Assembly does not have sign.

### ISSUE THREAD

**Issue by Mavrin** [digitalcreations/autoprefixer#1]
Could you sign your assembly? Now i cannot use your assembly from NuGet, because i have libraries in my project, which have sign.

**Comment by vegardlarsen** [comment]
@Mavrin I will have a look at getting that done on Monday. Thanks for letting me know.

**Comment by vegardlarsen** [comment]
@Mavrin Since our certificate had expired, I've had to order a new one. It will take a little while before it arrives.

**Comment by Mavrin** [comment]
@vegardlarsen It is cool. Thank you for quick answer.
